### ISSUE TITLE
Some Minor Changes 

### ISSUE THREAD

**Issue by PowerLevel9000** [rahuldurgapal/College-Project#1]
# Great work so far 🧑‍🏫🧑‍🏫 congrats for effort

## These are just Suggestions to make your project as pro

- [x]  Always  use separate [CSS file](https://developer.mozilla.org/en-US/docs/Web/CSS) for styling
- [x] Be professional as much as possible with a readme 
- [x]  Always have a demo deployment

![BrilliantWellDoneGIF](https://user-images.githubusercontent.com/116451144/213189228-d49acdd4-d1ca-4e02-9ceb-b9b5b7d01079.gif)

**Comment by mearjuntripathi** [comment]
thanks man we are thank for your appreciation.

**Comment by mearjuntripathi** [comment]
can you help us to creation of an readme file because we didn't know it

**Comment by PowerLevel9000** [comment]
hi @mearjuntripathi @rahuldurgapal 

# Use this one as an [template](https://github.com/PowerLevel9000/Dynamic-Event-Template/edit/master/README.md) I am pretty sure that you can observe code and some changes to look like yours 

in vscode you can preview your md file `ctrl + shift v`
form that templated copy whole code and made some changes according to you

**Comment by mearjuntripathi** [comment]
Resolved
